### ISSUE TITLE
Objc : Unable to locate test source file ****.swift

### ISSUE THREAD

**Issue by egr-ext** [Backelite/sonar-swift#242]
**Describe the bug**
The sonar report has 0 tests reported but the coverage is ok.

I saw these warnings:

INFO: Processing Surefire report TEST-report.xml
INFO: Unable to locate test source file Tests_GenericViewController.swift
INFO: Unable to locate test source file Tests_GenericViewController.m
INFO: Unable to locate test source file Tests_GenericViewController.swift

But as my project is in Objective C the test file names end with .m not .swift.
So the tool does not find the files.

**Comment by davidy4ng** [comment]
From those logs, it looks like your test is contained in a test class named GenericViewController (wether it's swift or objective-c).

-Did you set the `sonar.tests` path property in sonar-project.properties file?
-Make sure your test class file is in that path (or in a folder in that path)
-Make sure your test class name matches its file name.

**Comment by egr-ext** [comment]
Hi David, here are my answers:

-Did you set the sonar.tests path property in sonar-project.properties file?
Yes: 
sonar.tests=MyApp-unitTests

it is the directory where the tests files are.

-Make sure your test class file is in that path (or in a folder in that path)
Yes they are
-Make sure your test class name matches its file name.
Yes : class name: Tests_GenericViewController and the class file Tests_GenericViewController.m


My understanding is that the tool look for Tests_GenericViewController**.swift** but it should be Tests_GenericViewController.**m** ???

**Comment by gaelfoppolo** [comment]
Did you set `sonar.language`?

**Comment by davidy4ng** [comment]
@egr-ext actually it looks for both. That's why you also have the log
```INFO: Unable to locate test source file Tests_GenericViewController.m```

Can you provide a sample of your TEST-report.xml file?

**Comment by egr-ext** [comment]
> Did you set `sonar.language`?

yes: sonar.language=objc

**Comment by egr-ext** [comment]
> @egr-ext actually it looks for both. That's why you also have the log
> `INFO: Unable to locate test source file Tests_GenericViewController.m`
> 
> Can you provide a sample of your TEST-report.xml file?

here is an extract:
```
<?xml version='1.0' encoding='UTF-8'?>
<testsuites name='Notico-unitTests.xctest' tests='504' failures='0'>
  <testsuite name='Tests_AngelContactGenericTableViewCell' tests='6' failures='0'>
    <testcase classname='Tests_AngelContactGenericTableViewCell' name='testDrawImage' time='0.006'/>
    <testcase classname='Tests_AngelContactGenericTableViewCell' name='testSelectAndShowBellIcon' time='0.005'/>
    <testcase classname='Tests_AngelContactGenericTableViewCell' name='testUpdateViewWithCompany' time='0.001'/>
    <testcase classname='Tests_AngelContactGenericTableViewCell' name='testUpdateViewWithContact' time='0.003'/>
    <testcase classname='Tests_AngelContactGenericTableViewCell' name='testUpdateViewWithInvitationReceived' time='0.001'/>
    <testcase classname='Tests_AngelContactGenericTableViewCell' name='testWriteAlertLabel' time='0.002'/>
  </testsuite>
  <testsuite name='Tests_AngelContactsAddressBookViewController' tests='2' failures='0'>
    <testcase classname='Tests_AngelContactsAddressBookViewController' name='testGetCreatedPerson' time='0.009'/>
    <testcase classname='Tests_AngelContactsAddressBookViewController' name='testSelectCreatedPerson' time='0.010'/>
  </testsuite>
```

**Comment by gaelfoppolo** [comment]
The classname should be `Tests.AngelContactGenericTableViewCell`and not `Tests_AngelContactGenericTableViewCell`, for example.
Does your filename contains a `+` or `-`?
PR #239 should fix this issue then.

**Comment by egr-ext** [comment]
The filename is Tests_AngelContactGenericTableViewCell.m

**Comment by egr-ext** [comment]
> The classname should be `Tests.AngelContactGenericTableViewCell`and not `Tests_AngelContactGenericTableViewCell`, for example.
> Does your filename contains a `+` or `-`?
> PR #239 should fix this issue then.

I tried with backelite-sonar-swift-plugin-0.4.5.jar but I still does NOT have the number pf tests reported.

Is it an issue with tests files name containing "_" ?

**Comment by gaelfoppolo** [comment]
Indeed I think your issue is related to that.
The plugin is looking to a dot sepator and since yours is an underscore, it does not found it.
Maybe we should add the capability to support both.
Could you try removing the understore to see if the issue dissapears?

**Comment by egr-ext** [comment]
Hi Gael,

Yes but no success again:
1/ I just changed the file name and class name to TestsAngelContactGenericTableViewCell
2/ ran the analysis 
-> in Sonar I can see all indicators (coverage) but the number of tests is still missing.

I have no clue ....

**Comment by davidy4ng** [comment]
Which version of xcode and xcpretty do you use?

Looking back at your TEST-report.xml file, I see that the value of classname is : `Tests_AngelContactGenericTableViewCell`

In mine, I have the package name as a prefix, something like `MyTests.MyClassnameTests`.

Here is how it currently works: given a test report, a test case with classname `MyTests.MyClassnameTests`, the plugin will replace `.` by `/`, to get a hypothetical path for the test class.

So it searches for `MyTests/MyClassnameTests.swift` or `MyTests/MyClassnameTests.m`.

If no file is found, it then takes the last path component, here `MyClassnameTests.swift` or `MyClassnameTests.m` and search for any file with that name in the tests source folder you provided in your sonar-project.properties with the key `sonar.tests`

If nothing is found, it can't provide the tests to your SonarQube report.

Does it help?

**Comment by egr-ext** [comment]
> Which version of xcode and xcpretty do you use?
Xcode: Version 10.3 (10G8)
xcpretty: 0.3.0

> 
> Looking back at your TEST-report.xml file, I see that the value of classname is : `Tests_AngelContactGenericTableViewCell`
> 
> In mine, I have the package name as a prefix, something like `MyTests.MyClassnameTests`.
I can see that on a swift project. On an Obc it seems it is not prefixed
> 
> Here is how it currently works: given a test report, a test case with classname `MyTests.MyClassnameTests`, the plugin will replace `.` by `/`, to get a hypothetical path for the test class.
> 
> So it searches for `MyTests/MyClassnameTests.swift` or `MyTests/MyClassnameTests.m`.
> 
> If no file is found, it then takes the last path component, here `MyClassnameTests.swift` or `MyClassnameTests.m` and search for any file with that name in the tests source folder you provided in your sonar-project.properties with the key `sonar.tests`
> 
> If nothing is found, it can't provide the tests to your SonarQube report.
> 

My project file structure is like that :
./MyApp/source/**** -> all source files
./MyApp-unitTests/Tests_******.m  -> all test files
> Does it help?

**Comment by egr-ext** [comment]
Anyway can we re-open this issue ?

**Comment by davidy4ng** [comment]
Your scan command seems to be running directly on test scheme.
Try running it on your app scheme instead. If your project is setup correctly, it should run the related test scheme.

That may be the reason why your junit report file doesn't include the package name as a prefix.

**Comment by egr-ext** [comment]
I get the same result. They are not prefixed with package name.

One new info:

I just created a clean project with Xcode called MyApp (the standard 1 ViewController app , in language Objc). 
I ran the analysis on the app scheme on this brand new project.
The number of tests still does not appear on SonarQube. The others metrics appear.

**Comment by gaelfoppolo** [comment]
Can you provide this project sample so we can reproduce? (attach the zip here)

**Comment by egr-ext** [comment]
Here it is:
[MyApp.zip](https://github.com/Backelite/sonar-swift/files/3544787/MyApp.zip)

**Comment by gaelfoppolo** [comment]
Looks like the Junit is malformated.
Please use the .sh script to compare and fix your Fastlane integration.

**Comment by davidy4ng** [comment]
You might also want to have a look at my PR https://github.com/Backelite/sonar-swift/pull/241

For fastlane integration with the same behavior as the bash script

**Comment by egr-ext** [comment]
> Looks like the Junit is malformated.
> Please use the .sh script to compare and fix your Fastlane integration.

Sorry I don't understand which script ?

**Comment by gaelfoppolo** [comment]
The script detailed in the README, section [Launching the analysis](https://github.com/Backelite/sonar-swift#launching-an-analysis).

**Comment by egr-ext** [comment]
OK.

The script keep saying some swift parameters are missing ex: sonar.swift.appScheme parameter is missing in sonar-project.properties. You must specify which scheme is used to build your application.

But I have a Objective C project  ... DO I have to set swift parameters ?

Plus I use Fastlane so I use this script to understand but it is not easy to find why it does not work with Fastlane

**Comment by egr-ext** [comment]
So the script run but at the end I have an error with no information (I set the option -v to debug):

14:57:25.916 INFO: Calculating CPD for 0 files
14:57:25.916 INFO: CPD calculation finished
14:57:26.019 INFO: ------------------------------------------------------------------------
14:57:26.020 INFO: EXECUTION FAILURE
14:57:26.020 INFO: ------------------------------------------------------------------------
14:57:26.020 INFO: Total time: 4.537s
14:57:26.041 INFO: Final Memory: 11M/47M
14:57:26.041 INFO: ------------------------------------------------------------------------
14:57:26.041 ERROR: Error during SonarQube Scanner execution
java.lang.NullPointerException
	at org.sonarsource.scm.git.GitScmProvider.revisionId(GitScmProvider.java:107)
	at org.sonar.scanner.report.MetadataPublisher.addScmInformation(MetadataPublisher.java:126)
	at org.sonar.scanner.report.MetadataPublisher.publish(MetadataPublisher.java:98)
	at org.sonar.scanner.report.ReportPublisher.generateReportFile(ReportPublisher.java:150)
	at org.sonar.scanner.report.ReportPublisher.execute(ReportPublisher.java:135)
	at org.sonar.scanner.phases.PublishPhaseExecutor.executeOnRoot(PublishPhaseExecutor.java:49)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:79)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:166)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:300)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:295)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:269)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:82)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:131)
	at org.sonar.batch.bootstrapper.Batch.doExecuteTask(Batch.java:116)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:71)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:185)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:137)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
14:57:26.042 ERROR: 
14:57:26.042 ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.

**Comment by egr-ext** [comment]
So I ran the script run-sonar-swift.sh.

I have the same result.

TEST-report.xml:

```
<?xml version='1.0' encoding='UTF-8'?>
<testsuites name='MyAppUITests.xctest' tests='3' failures='0'>
  <testsuite name='MyAppTests' tests='2' failures='0'>
    <testcase classname='MyAppTests' name='testExample' time='0.001'/>
    <testcase classname='MyAppTests' name='testPerformanceExample' time='0.338'/>
  </testsuite>
  <testsuite name='MyAppUITests' tests='1' failures='0'>
    <testcase classname='MyAppUITests' name='testExample' time='4.708'/>
  </testsuite>
</testsuites>

```

And I don't have the numer of tests.
<img width="1250" alt="sonar" src="https://user-images.githubusercontent.com/28352240/63773996-9f26ef00-c8dc-11e9-9985-f447868636fb.png">

Here is the zip of the objc project:
[MyApp.zip](https://github.com/Backelite/sonar-swift/files/3546232/MyApp.zip)

**Comment by egr-ext** [comment]
I'am 100% convinced that it is a bug for Objective C source code only.
Can someone direct me to the code that process these files ?

**Comment by davidy4ng** [comment]
This is the code that process it

https://github.com/Backelite/sonar-swift/blob/develop/objclang/src/main/java/com/backelite/sonarqube/objectivec/surefire/ObjectiveCTestFileFinder.java

**Comment by egr-ext** [comment]
J'ai pris des log. 
Cette ligne 39 ne trouve pas le fichier alors que le filename est bon et dans le path:
`        FilePredicate fp = fileSystem.predicates().hasPath(fileName);`

J'investigue ...

**Comment by egr-ext** [comment]
My skills are very limited in Java but what I see is:
`fileSystem.baseDir()` return the path of my project directory NOT the path of the tests directory.
i.e. it returns 
`/Users/egr-dw/Projets/tests/MyApp`
Instead of 
`/Users/egr-dw/Projets/tests/MyApp/MyApp/MyAppTests`

I don't know what fileSystem.predicates() should do ?

**Comment by egr-ext** [comment]
I found the issue !!!
Fixed by this PR #248

**Comment by davidy4ng** [comment]
Thanks @egr-ext

**Comment by gaelfoppolo** [comment]
Nice work @egr-ext! I'll have a look at your PR!

**Comment by zippy1978** [comment]
PR merged !
