### ISSUE TITLE
"Unable to locate test source file" -> 0 tests count

### ISSUE THREAD

**Issue by gooner22** [Backelite/sonar-swift#34]
While uploading analysis to sonar, I get 0 tests count

I noticed following log
> INFO: Unable to locate test source file LogicTests/Test.swift

Env:

- sonar 5.4
- sonar-swift 0.2.3
- fastlane to create reports

Notes: 

- reports folder contains TEST-junit.xml as required by sonar-swift plugin 0.2.3
- sonar.junit.reportsPath=.Build/reports/unit_test_output/

**Comment by mgrebenets** [comment]
@gooner22 

I used `fastlane`'s `scan` tool too and got similar issue.
My JUnit test report looked like this:

```xml
xml version='1.0' encoding='UTF-8'?>
<testsuites tests='100' failures='0'>
  <testsuite name='MyUnitTestTargetName.MyClassName' tests='2' failures='0'>
```

The `MyUnitTestTargetName` is the name of unit tests target in my project.
This kind of report would not be picked up by Sonar then.
So I had to patch the report and remove the `MyUnitTestTargetName.` part, to make it look like this:

```xml
xml version='1.0' encoding='UTF-8'?>
<testsuites tests='100' failures='0'>
  <testsuite name='MyClassName' tests='2' failures='0'>
```

After this my test reports were properly picked up by Sonar plugin.

I'm not sure yet which tool is to blame here. Is it `fastlane`/`scan` putting extra info in the test suite name or is it `sonar-swift` not being flexible enough to strip it out.

I think both tools are the problem here :)
`scan` should have an option to control generation of JUnit reports, `sonar-swift` should be flexible and understand all kinds of prefixes.

**Comment by zippy1978** [comment]
Hi,

I just fixed a bug with Junit Fastlane report naming and the plugin. See https://github.com/Backelite/sonar-swift/issues/29

I will release the fix soon.

Regards

**Comment by zippy1978** [comment]
This is fixed in release 0.2.4

**Comment by gooner22** [comment]
@zippy1978 thanks!

**Comment by Pierre-Loup** [comment]
Issue still present in the version 0.2.4
Pull request #28 resolve the issue but hasn't been merge yet.

**Comment by gooner22** [comment]
still relevant.

```
[00:40:06]: ▸ [35mINFO: Unable to locate test source file MY_MODULE/ATests.swift[0m
[00:40:06]: ▸ [35mINFO: Unable to locate test source file MY_MODULE/BTests.swift[0m
```
