### ISSUE TITLE
ERROR: Lizard Report not found

### ISSUE THREAD

**Issue by auryn31** [Backelite/sonar-swift#86]
Hey Guys,
I get every time the error:
ERROR: Lizard Report not found
and I don't now, what to do :-(
pleas help me

# .properties
sonar.projectKey=
sonar.projectName=
sonar.projectVersion=1.0
sonar.language=swift
sonar.profile=SwiftLint
sonar.sources=
sonar.swift.workspace=LottieViewer.xcworkspace
sonar.swift.project=LottieViewer.xcodeproj
sonar.swift.appScheme=Debug
sonar.swift.simulator=platform=iOS Simulator,name=iPhone 6,OS=9.2
sonar.objectivec.excludedPathsFromCoverage=.*Tests.*,.*Specs.*
sonar.objectivec.simulator=platform=iOS Simulator,name=iPhone SE,OS=10.3
sonar.objectivec.appScheme=Enterprise

# error:

`ERROR: Lizard Report not found .../sonar-reports/lizard-report.xml
java.io.FileNotFoundException: .../sonar-reports/lizard-report.xml (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:623)
	at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:148)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:805)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:205)
	at org.sonar.plugins.swift.complexity.LizardReportParser.parseReport(LizardReportParser.java:65)
	at org.sonar.plugins.swift.complexity.LizardSensor.parseReportsIn(LizardSensor.java:69)
	at org.sonar.plugins.swift.complexity.LizardSensor.analyse(LizardSensor.java:60)
	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:57)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:49)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:78)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:182)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:247)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:242)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:232)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:115)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:116)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)`

**Comment by auryn31** [comment]
Problem solved
found the error
have to turn on lizard :-D
thanks

**Comment by CarlesEstevadeordal** [comment]
How do you turn on lizard?

**Comment by navjotbedi** [comment]
Lizard is turned ON for me, but still getting this error. Please help.

**Comment by AhmedAskar** [comment]
I have the same error however Lizard is turned on

**Comment by TorstenKruse** [comment]
We have the sonar-swift plugin also installed for our iOS developers building their CI jobs on MacOS.
But I get this error in maven builds of java projects on linux machines. 

How can I avoid this?

**Comment by ace128** [comment]
I would also like to know if there's a way to suppress these error messages when doing builds/scans of non-swift projects. Anyone have any ideas?

**Comment by niltongouveajr** [comment]
> We have the sonar-swift plugin also installed for our iOS developers building their CI jobs on MacOS.
> But I get this error in maven builds of java projects on linux machines.
> 
> How can I avoid this?

Same here and I would like a way to supress these error messages...

**Comment by Madh93** [comment]
We have the same problem. When we scan java o other languages projects we get this error.

**Comment by niltongouveajr** [comment]
This issue is closed. Would it be necessary to create a new issue for it to be handled since we are trying to suppress the Lizard error message in non-Swift projects?

**Comment by Madh93** [comment]
@TorstenKruse @ace128 @niltongouveajr I have opened the next PR https://github.com/Backelite/sonar-swift/pull/174

I have built a [.jar](https://github.com/Madh93/sonar-swift/releases/tag/0.4.1.custom) with these changes.

**Comment by zhaoyubetter** [comment]
not work

**Comment by gigaga** [comment]
We have the same error for any project even if for non-swift projects :(

**Comment by niltongouveajr** [comment]
> We have the same error for any project even if for non-swift projects :(

Try replacing the current plugin with the jar file made by @ Madh93. It worked for me.

**Comment by Madh93** [comment]
I have to say this was fixed in [0.4.2](https://github.com/Backelite/sonar-swift/releases/tag/0.4.2).

**Comment by gigaga** [comment]
> I have to say this was fixed in [0.4.2](https://github.com/Backelite/sonar-swift/releases/tag/0.4.2).

The related commit (acaefb2) seems not be this tag: https://github.com/Backelite/sonar-swift/compare/0.4.2...develop

**Comment by costaneto222** [comment]
Still happens here

INFO: Sensor Lizard [backelitesonarswiftplugin]
INFO: Processing complexity report 
ERROR: Lizard Report not found /.../sonar-reports/lizard-report.xml
java.io.FileNotFoundException: /.../sonar-reports/lizard-report.xml (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
.
.
.

**Comment by soufianeEssabbane** [comment]
any news on this ? I have the same issue ...

**Comment by costaneto222** [comment]
Hi!
The solution for me was:
- download the lizard folder project on https://github.com/terryyin/lizard
- open terminal
- make 'cd' command to lizard recent downloaded folder
- execute the command 'sudo python setup.py install'
- done, lizard start works

To install python, you can follow the python org tutorial
https://docs.python-guide.org/starting/install3/osx/

**Comment by soufianeEssabbane** [comment]
@costaneto222  thank you I'll give it a try and let others know

**Comment by soufianeEssabbane** [comment]
@costaneto222 thank you, now we can get the report but after running the script there's an error while processing the report : 

[Fatal Error] lizard-report.xml:1:1: Premature end of file.

What extension version are you using ? 

Thank you

**Comment by costaneto222** [comment]
Hi! \o/

@soufianeEssabbane, I'm currently using this versions:

Lizard - 1.15.6
SonarQube - 6.7.6
sonar-swift plugin - 0.4.2

Is that what you're asking for?

**Comment by soufianeEssabbane** [comment]
Thank you very much ! I'll check again with the 0.4.2 and confirm for traceability

**Comment by soufianeEssabbane** [comment]
@costaneto222 are you able to get the same dashboard as in 

![](https://github.com/Backelite/sonar-swift/blob/develop/screenshot.png)

I'm getting only some code smell with poor informations like "naming convention" ... and in the sonar-reports bundle in the best I'm getting only the lizard report ... 

can u advise ?

**Comment by costaneto222** [comment]
Probably will be better if you open a new issue/question with all debug information from the terminal. This could be problem with other library, not necessarily lizard.
Execute your run-sonar-swift.sh with ' -v' to get the full debug information ;)

**Comment by costaneto222** [comment]
Hi there!
Yes, not exactly like showed in the readme because that overview is from 2016, but yes, all features are working fine now.
Coverage, Code Smells, Duplications...
